### ISSUE TITLE
move abs()

### ISSUE THREAD

**Issue by aminnj** [cmstas/NanoTools#2]
Spotted this just now. Since there's only electrons and muons, this isn't a bug here, but should be fixed for consistency (also see if there are any similar places that could actually be bugged.

https://github.com/cmstas/NanoTools/blob/b1a90dc21617ad01c7d629a2439a58a2d4c21472/NanoCORE/IsolationTools.cc#L9-L13

(`abs` should only wrap `id`)

**Comment by jkguiang** [comment]
Fixed here: https://github.com/cmstas/NanoTools/commit/b2470c04764d6ce90051a9b2da58e5bed0de6fb7
